### ISSUE TITLE
add to uFuzzy benchmark

### ISSUE THREAD

**Issue by leeoniya** [localvoid/ndx#40]
hey @localvoid just discovered this lib.

i'm opening this issue to remind myself to add `ndx` to my [search lib bench](https://github.com/leeoniya/uFuzzy#benchmark). as with most of your work, i'm excited to try it :)

**Comment by leeoniya** [comment]
added it here: https://leeoniya.github.io/uFuzzy/demos/compare.html?libs=uFuzzy,ndx&search=super%20mario

why can't fulltext search engines rank exact matches better :confused:

**Comment by localvoid** [comment]
> why can't fulltext search engines rank exact matches better

Tradeoffs :) I've implemented it for a specific use case when all documents were stored in an indexed db, with a dynamic index (add/update/remove) and I didn't want to store token locations. I also wanted to implement it, so that inverted index were splitted into many chunks and stored in an indexed db, but it was good enough for my use case.

For a huge static dataset I would definitely choose an [FSM](https://blog.burntsushi.net/transducers/) based index.

**Comment by leeoniya** [comment]
:+1:
